/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @Test void solutionTest1() {
        assertEquals("adbecf", Solution.solution("abc", "def"));
    }

    @Test void solutionTest2() {
        assertEquals("hweolrllod", Solution.solution("hello", "world"));
    }
}
