/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import kotlin.test.Test
import kotlin.test.assertEquals

class SolutionTest {
    @Test fun solutionTest1() {
        assertEquals("a1b2c3", solution("abc", "123"))
    }
}
