/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

 fun solution(word1: String, word2: String): String {
    var longer_word: String;
    var shorter_length: Int;
    var sb = StringBuilder();

    if (word1.length > word2.length) {
        shorter_length = word2.length;
        longer_word = word1;
    } else {
        shorter_length = word1.length;
        longer_word = word2;
    }

    word1.zip(word2).forEach {
        sb.append(it.first);
        sb.append(it.second);
    }

    sb.append(longer_word.substring(shorter_length, longer_word.length));

    return sb.toString();

 }

fun main() {
    println(solution("abc", "def"))
}
